#default delays
can_delay: 0  #wait time after detecting can placement
purge_time_seconds: 3 #seconds to purge can with co2
post_purge_delay: 1 #seconds to wait before starting beer fill
overfill_delay: .1  #seconds to wait before stopping beef flow after fill sensor triggers
clean_time_seconds : 4


#default sensor calibration
nominal_proximity_cutoff: .5    #value when prox. sensor is considered HIGH
nominal_fill_resistivity: .5   #value when fill sensor is considered HIGH

#calibration delays
calibration_stage_delay_seconds: 10
calibration_stage_time: 1


#proximity settings
proximity_sensitivity: 10
priximity_decision_ration: .8

filler_list:
  -   name : Lab
      co2_gpio : 2
      beer_gpio :  3
      proximity_gpio : 11
      fill_gpio : 23

  -   name : Collie
      co2_gpio : 4
      beer_gpio : 17
      proximity_gpio : 5
      fill_gpio : 24

  -   name : Poodle
      co2_gpio : 27
      beer_gpio : 22
      proximity_gpio : 6
      fill_gpio : 25

  -   name : Shepherd
      co2_gpio : 10
      beer_gpio : 9
      proximity_gpio : 11
      fill_gpio : 8


# GPIO    PIN   Function
# 2       3     relay 1
# 3       5     relay 2
# 4       7     relay 3
# 17      11    relay 4
# 27      13    relay 5
# 22      15    relay 6
# 10      19    relay 7
# 9       21    relay 8
# 11      23    PS1
# 5       29    PS2
# 6       31    PS3
# 13      33    PS4
# 23      16    FS1
# 24      18    FS2
# 25      22    FS3
# 8       24    FS4
#
#
#