#default delays
can_delay: 0  #wait time after detecting can placement
purge_time_seconds: 3 #seconds to purge can with co2
post_purge_delay: 1 #seconds to wait before starting beer fill
overfill_delay: .1  #seconds to wait before stopping beef flow after fill sensor triggers
clean_time_seconds : 4


#default sensor calibration
nominal_proximity_cutoff: .5    #value when prox. sensor transitions from CLOSE(0) to OPEN(1)
nominal_fill_resistivity: .5   #value when fill sensor is considered HIGH

#calibration delays
calibration_stage_delay_seconds: 10
calibration_stage_time: 1


#proximity settings
proximity_sensitivity: 10
priximity_decision_ration: .8

filler_list:
  -   name : Lab
      co2_gpio : 2
      beer_gpio :  3
      proximity_gpio : 11
      fill_gpio : 23

